version: '3.8'

services:

  api-gateway:
    build:
      context: ./Docker/api-gateway
      dockerfile: Dockerfile 
       
  keycloak:
    build:
      context: ./Docker/keycloak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8443:8443"