name: Docker images for API Gateway and Keycloak
on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy_api_gateway_for_dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  
      - name: Login to Docker Hub for API Gateway
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push API Gateway image
        uses: docker/build-push-action@v5
        with:
          #context: ./api-gateway-docker  # Path to the API Gateway Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway-dev:latest
  
      # - name: Trigger Jenkins Job
      #   run: |
      #     curl -X POST -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_PAT}} "https://jenkins-mg-infra-group.apps.ocp5-inholland.joran-bergfeld.com/job/api-gateway-job/build?token=${{ secrets.JENKINS_REMOTE_TRIGGER_TOKEN }}"

  # deploy_api_gateway_for_prod:
  #   runs-on: ubuntu-latest
  #   if: github.event_name == 'push' && github.ref == 'refs/heads/main
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4

  #     - name: Login to Docker Hub for API Gateway dev
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}
          
  #     - name: Build and push API Gateway dev image
  #       uses: docker/build-push-action@v5
  #       with:
  #         #context: ./api-gateway-docker  # Path to the API Gateway Dockerfile
  #         push: true
  #         tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway-image:latest
  
  #     - name: Trigger Jenkins Job
  #       run: |
  #         curl -X POST -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_PAT}} "https://jenkins-mg-infra-group.apps.ocp5-inholland.joran-bergfeld.com/job/api-gateway-job/build?token=${{ secrets.JENKINS_REMOTE_TRIGGER_TOKEN }}"
