name: Docker images for API Gateway and Keycloak
on:
  push:
    branches:
      - dev

jobs:
  build_api_gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release
        
      - name: Test
        run: dotnet test 
        
      - name: Login to Docker Hub for API Gateway
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Gateway image
        uses: docker/build-push-action@v5
        with:
          #context: ./api-gateway-docker  # Path to the API Gateway Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway-image-dev:latest
  
      - name: Trigger Jenkins Job
        run: |
          curl -X POST -u ${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_PAT}} "https://jenkins-mg-development.apps.ocp5-inholland.joran-bergfeld.com/job/api-gateway-job/build?token=${{ secrets.JENKINS_REMOTE_TRIGGER_TOKEN }}"
