name: Docker images for API Gateway and Keycloak

on:
  push:
    branches:
      - main

jobs:
  build_api_gateway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub for API Gateway
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API Gateway image
        uses: docker/build-push-action@v5
        with:
          context: ./api-gateway-docker  # Path to the API Gateway Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/api-gateway-image:latest

  build_keycloak:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub for Keycloak
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Keycloak image
        uses: docker/build-push-action@v5
        with:
          context: ./keycloak  # Path to the Keycloak Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/keycloak-image:latest
